#:schema node_modules/wrangler/config-schema.json
name = "magic-ball-app"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "magic-ball-db"
database_id = "00000000-0000-0000-0000-000000000000" # Replace with real ID when deployed
migrations_dir = "drizzle"
